# Permalinks
permalink:           pretty

# Setup
title:               Jackzhangpython
tagline:             猿
url:                 http://jackzhangpython.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jackzhangpython
  url:               https://twitter.com/jackzhangpython
  email:             jackzhang.python@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jackzhangpython/jackzhangpython.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
